# Generated by Django 4.0.3 on 2022-03-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_course_department_master_studentcourse_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='Likes', to='university.student'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('LIKE', 'LIKE'), ('Dislike', 'Dislike')], default='LIKE', max_length=10)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.master')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
            ],
        ),
    ]
